name: gandalf
description: A new Flutter project.
publish_to: "none"
version: 3.3.0+11

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  riverpod: 2.6.1
  flutter_riverpod: 2.6.1
  icons_plus: 5.0.0
  universal_io: 2.2.2
  font_awesome_flutter: 10.8.0
  modal_bottom_sheet: 3.0.0

  google_mobile_ads: 5.2.0
  firebase_core: 3.8.0
  firebase_analytics: 11.3.5
  firebase_messaging: 15.1.5
  firebase_crashlytics: 4.1.5
  firebase_performance: 0.10.0+10

  url_launcher: 6.3.1
  shared_preferences: 2.3.3
  share_plus: 10.1.2
  # video_player: 2.9.2
  media_kit: 1.1.11 # Primary package.
  media_kit_video: 1.2.5 # For video rendering.
  media_kit_libs_video: 1.0.5 # Native video dependencies.

  video_player: 2.9.2
  video_player_media_kit: 1.0.5
  media_kit_libs_android_video: any
  media_kit_libs_ios_video: any
  media_kit_libs_macos_video: any
  media_kit_libs_windows_video: any
  media_kit_libs_linux: any

  icons_launcher: 3.0.0 
  flutter_native_splash: 2.4.2

dev_dependencies:
  path: 1.9.0
  yaml: 3.1.2
  io: 1.0.4

flutter_icons:
  includes:
    - mco

flutter:
  uses-material-design: true
  assets:
    - assets/video.mp4

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/icons/logo-alpha.png"
  android: true
  ios: true
  web: true