name: gandalf
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  share_plus: 10.1.2
  provider: 6.1.2
  url_launcher: 6.3.1
  icons_plus: 5.0.0

  google_mobile_ads: 5.2.0
  in_app_purchase: 3.2.0
  firebase_core: 3.5.0
  firebase_analytics: 11.3.2
  firebase_messaging: 15.1.2
  firebase_crashlytics: 4.1.2
  firebase_performance: 0.10.0+7

  video_player: 2.9.2

dev_dependencies:
  path: 1.9.0
  yaml: 3.1.2
  io: 1.0.4

flutter_icons:
  includes:
    - mco

flutter:
  uses-material-design: true
  assets:
    - assets/video.mp4
